#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${prod_db_password:root}
    url: jdbc:mysql://${prod_db_url:localhost:3306}/b2b?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: ${prod_db_user:root}


# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug




