package io.github.talelin.latticy.vo;

import io.github.talelin.latticy.dto.ProductDTO;
import io.github.talelin.latticy.dto.SkuDTO;
import io.github.talelin.latticy.model.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
public class PrintDataVO extends ImsContractDO {
    private String invoiceId; // generated by backend
    private CmsClientInfoDO clientInfo;
    private List<ImsContractProductDO> products;
    private List<SkuDTO> skus;
    private List<SpuInfoWithAttr> spus;
    private UserDO currentUser;
}
