drop table if exists cms_client_info;
drop table if exists cms_client_interest;
drop table if exists cms_client_follow_log;
drop table if exists cms_client_files;
drop table if exists cms_contract;


create table cms_client_info
(
    id                   bigint not null auto_increment comment 'id',
    country              char(50),
    client_name          char(250),
    company_name         char(250),
    contact_methods      text comment 'JSON string of array',
    code                 char(250) comment 'generated by frontend code',
    client_level                char(250) comment 'should be int(enum), optimise later',
    industry             char(250) comment 'should be int(enum), optimise later',
    source               char(250),
    owned_by             bigint comment 'user id, if not owned by anyone, should be in public sea(公海)',
    create_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) comment 'if 30 days not update, put to public sea, update means 1, change basic info, 2, create client follow log',
    delete_time datetime(3)               DEFAULT NULL,
    primary key (id)
);

create table cms_client_interest
(
    id                   bigint not null auto_increment comment 'id',
    client_id            bigint,
    product_id           bigint comment '0 id means product need to be purchased',
    notes                text comment 'if product_id is 0, needs to add a note',
    create_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    delete_time datetime(3)               DEFAULT NULL,
    primary key (id)
);

create table cms_client_follow_log
(
    id                   bigint not null auto_increment comment 'id',
    client_id            bigint,
    user_id              bigint comment 'followed by which user',
    content              text comment 'follow content',
    create_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) comment 'means follow time',
    update_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) comment 'nearly not possible to update this',
    delete_time datetime(3)               DEFAULT NULL,
    primary key (id)
);

create table cms_client_files
(
    id                   bigint not null auto_increment comment 'id',
    client_id            bigint,
    file_name            varchar(250),
    file_url             text,
    create_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) comment 'means follow time',
    update_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) comment 'nearly not possible to update this',
    delete_time datetime(3)               DEFAULT NULL,
    primary key (id)
);

create table cms_contract
(
    id                   bigint not null auto_increment comment 'id',
    contract_date        date comment 'could be selected by sales in frontend',
    delivery_date        date comment 'could be selected by sales in frontend',
    client_id            bigint,
    total_amount         text comment 'modify later, by on currency',
    actual_delivery_fee  text comment 'modify later, by on currency',
    other_fee            text comment 'modify later',
    other_fee_comment    text,
    payment_method       varchar(250),
    product_ids          text comment 'should be sku, separated by ,',
    notes                text comment 'contract notes, handwritten by sales',
    payment_status       text comment '支付预付款|款项收齐|其他',
    payment_pre_amount   text,
    payment_other_notes  text,
    owned_by             bigint comment 'user id',
    raw_cost             text comment 'not modify by sales, only admin',
    review_status        text comment '待审批|已审批 -- 业务填写款项收齐提示是否进入审批状态 审批状态 will show up in admins panel',
    create_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) comment 'means follow time',
    update_time datetime(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) comment 'nearly not possible to update this',
    delete_time datetime(3)               DEFAULT NULL,
    primary key (id)
);

